language: node_js
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_b516168dc854_key -iv $encrypted_b516168dc854_iv
  -in id_.travis/rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'johny.zheng'
- git config --global user.email 'shun.johny@gmail.com'
install:
- npm install
script:
- hexo clean
after_success:
- hexo d
cache:
  directories:
  - node_modules
env:
  global:
    secure: A6dss6VGfjgUaRNgOrC/5JTkMBOlk5d2ZO/LZXiRFcFCdPGEAyD4nk0WDQvEb+AsCnJIbISYk0uuX7TlNA2n/0+bXIESrAUnmUk18KidqmwqwngzJpGMU7NzpJPnxSbhUetb1mo+oh9HF2EJZ0w0J7S57SzqhX20j6RuexcX/xxTZ04kWi+Zav/HqQ9+Dy19qYxMY45z6OSiNcXV/Z7oPuwaluGvOFwTXLA6Jv+eTD3OgLMBxgdp2dAenqhVLb6c1h0wV3qQjkwPJQmC/MwUtZEmEg86QZWb+rV2Pw6LV+ou8ynDW2PIAt+RNgLpU7vNXG8FXmyRx36y5J3knKH4PYF9xKRzxTKLS5zH0VozdP5ylrM08XMdIngFr2bf/o0EoqTdHA/twbwme5P/AYB2H1rRzFIJ70f+ChL0jchqdIt4kgTyVIx10MeISg33Ye7aewT0zZQ6C0ZSAoNGf+1neX1fW/+g/EMKtQCfMM+i2LmGGSy+6WVhN38fyeLuE5n4wJf6af70Jr2OzA1IrXMGto2AV/UPQiP/2RrOOzJOl18FKO08mKTIIu6Yv/khPkNbOoh+hMBNnm9OkXPa0xaavcmw3LQR5TFz0jjxGTHJ4bO+FevZiwho8MPMQKEv9NWACguj33E19pOw8NV67kRVTSLu8Eyc24Bu580jlRCfZ3g=
