language: node_js
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'johny.zheng'
- git config --global user.email 'shun.johny@gmail.com'
install:
- npm install
script:
- hexo clean
after_success:
- hexo d
cache:
  directories:
  - node_modules
env:
  global:
    secure: ftWjVCB6YObQe3PEkK69rEN2RFroVqWAYtm9n2sqxsI12uqSU41OxPyP4IG7DLPWEBZ6VmFqzGrvQBs9lgkycHpWmG4N3oLnE3Spf9cqgQyo8hWkXardxYT5WqPtvcVRJJVL2xO8AVOMdPAMJRdB7qO37r/Mh+aWxE3BnM7A/kcVtM1zfbq9/DYzJIcx/xz0cjlscREiHpWSTF0LjxRozi5w43u0SBT6WnnYRCbby8IwL3fo8gLc8WldSShjCp7e1Z/Hg62B644dNL44s8uTql1im5eZEb+MMbpUwZR/zuWFuzNjKwGqY/sFdJicLc20TcNtriO2Faf1bYBM679dUCzbrqgDvD74bkXHljqex4mnnSv+viIx47c0jTG9mXpTsX+ffR4agElrNR4zBhQ/zyXw+LuXgUBAIjXFx59I/GodytEbixIWJ/nE0Kw2LaLetkp5jr6+q1XgvxNe+9fNg7LA8ScLf1znL2+SBrf9CiLa9ADJtbifIH9SYCDGQ9oOunfzEvBqSsPGe9xIrK2q+wTNvjZF/OsBtRhKrDfHhCnEHEH0dUu7zsI3Y8nUHSP6JV8z4ZCd+iL8RS2MS43Xdhmh2Pxp2a54Ez/XCfXaW4bvcVPErKo2wRxs8TfPahlQOqyUeoxOmh8kL+kMlLd3pISbvUZzN0HDBApvPRvFMks=
